format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
    code-tools: true
    code-fold: true
    code-summary: "Show code"
    css: styles/course.css
    embed-resources: true
    math: mathjax

  pdf:
    documentclass: book
    pdf-engine: lualatex
    keep-tex: true
    include-in-header: "styles/preamble.tex"
